blueprint:
  name: Motion detection
  description: Sets a room entity to occupied when motion is detected.
  domain: automation
  input:
    motion_sensor:
      name: Motion sensor
      description: The motion sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    person:
      name: Person
      description: This person must be home for the automation to trigger
      selector:
        entity:
          domain: person
    active_switch:
      name: Active switch
      description: This switch must be on for the automation to trigger
      selector:
        entity:
          domain: input_boolean
    occupied_boolean:
      name: Input boolean
      description: This input_boolean will be set on
      selector:
        entity:
          domain: input_boolean

mode: queued

trigger:
  platform: state
  to: 'on'
  entity_id: !input motion_sensor

condition:
  condition: and
  conditions:
  - condition: state
    entity_id: !input person
    state: home
  - condition: state
    entity_id: !input active_switch
    state: 'on'
action:
  - service: python_script.set_occupancy
    data:
      entity_id: !input occupied_boolean
