homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include conf/customize.yaml
  customize_glob:
    "scene.*_occupied":
      hidden: true
    "light.kitchen*":
      hidden: true
    "sensor.motion_sensor_*_2":
      icon: mdi:white-balance-sunny

config:

myhome: !include conf/myhome.yaml

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml

history:

recorder:
  purge_interval: 1
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - group
    entities:
      - sun.sun
      - sensor.date
      - binary_sensor.weekday
      - binary_sensor.dst
      - calendar.vacation

logbook:
  exclude:
    domains:
      - automation
      - group

http:

sun:

sensor:
  - platform: systemmonitor
    scan_interval: 30
    resources:
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
  - platform: time_date
    display_options:
      - date
  - platform: template
    sensors:
      bedroom_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_2_2", "battery_level") }}'
        entity_id:
          - sensor.motion_sensor_2_2
        unit_of_measurement: "%"
        friendly_name: "Bedroom sensor battery"
      bookcase_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_4_2", "battery_level") }}'
        entity_id:
          - sensor.motion_sensor_4_2
        unit_of_measurement: "%"
        friendly_name: "Bookcase sensor battery"
      living_room_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_10_2", "battery_level") }}'
        entity_id:
          - sensor.motion_sensor_10_2
        unit_of_measurement: "%"
        friendly_name: "Living room sensor battery"
      front_door_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_5_2", "battery_level") }}'
        entity_id:
          - sensor.motion_sensor_5_2
        unit_of_measurement: "%"
        friendly_name: "Front door sensor battery"
  - platform: openweathermap
    api_key: !secret weather_key
    name: owm_current
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - pressure
      - clouds
      - rain
      - weather_code
  - platform: openweathermap
    api_key: !secret weather_key
    name: owm_forecast
    forecast: true
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - pressure
      - clouds
      - rain
      - weather_code

binary_sensor:
  - platform: template
    sensors: !include_dir_merge_named binary_sensors/

hue:
  bridges:
    - host: 192.168.1.124
      filename: phue.conf

device_tracker:
- platform: !secret device_tracker_platform
  host: 192.168.1.1
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  http_id: !secret device_tracker_http_id
  track_new_devices: no

mysensors:
  gateways:
    - device: '127.0.0.1'
      tcp_port: 5003
      persistence_file: '/home/homeassistant/hass-config/mysensors.json'
  persistence: true
  version: '1.5'

group:
  living_room:
    name: Living Room
    entities:
    - light.living_room_standing
    - light.tv_left
    - light.tv_right
    - light.hyperion
  bedroom:
    name: Bedroom
    entities:
    - light.night_stand
    - light.dresser
  kitchen:
    name: Kitchen
    entities:
    - light.rgbw_15_1
    - light.rgbw_15_2
  hall:
    name: Hall
    entities:
    - light.hall

automation: !include_dir_merge_list automations/

script: !include_dir_merge_named scripts/

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.tomato.device_tracker: warning
    homeassistant.components.http: warning
    homeassistant.components.template.scene: info
    mysensors: info
    homeassistant.components.mysensors: info
    custom_components.myhome: debug

input_number:
  living_room_threshold:
    name: Living room threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: step
  kitchen_threshold:
    name: Kitchen threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: step
  bedroom_threshold:
    name: Bedroom threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: step
  hall_threshold:
    name: Hall threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: step

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Afternoon
      - Evening
      - Night
      - Asleep
    icon: mdi:format-list-bulleted
  media_mode:
    name: Media Mode
    options:
      - TV
      - Movie
      - Paused
      - Awake
      - Idle
      - "Off"
      - Disabled
    icon: mdi:format-list-bulleted
  current_theme:
    name: Theme
    options:
     - default
     - clear
     - clear-dark
     - amoled
     - blue_night
     - midnight
     - light
     - dark
    initial: clear
    icon: mdi:theme-light-dark

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:wrench
  myhome_active:
    name: Active
    icon: mdi:home-variant
  room_bedroom:
    name: Bedroom
    icon: mdi:hotel
  room_kitchen:
    name: Kitchen
    icon: mdi:silverware-spoon
  room_hall:
    name: Hall
    icon: mdi:glassdoor
  room_living_room:
    name: Living Room
    icon: mdi:television-classic
  autodark_theme:
    name: Auto-dark theme
    icon: mdi:theme-light-dark
  auto_living_room_standing:
    name: Auto update living room standing
  auto_living_room_tv:
    name: Auto update living room tv
  auto_kitchen:
    name: Auto update kitchen
  auto_bedroom:
    name: Auto update bedroom
  auto_hall:
    name: Auto update hall

python_script:

media_player:
  - platform: samsungtv
    name: Samsung TV
    host: 192.168.1.134
    port: 8001
    mac: "F8:77:B8:CD:B2:9A"
  - platform: androidtv
    name: Android TV
    host: 192.168.1.123
    adb_server_ip: 127.0.0.1
    #adbkey: "/home/homeassistant/hass-config/android/adbkey"
    scan_interval: 4
    state_detection_rules:
      com.amazon.amazonvideo.livingroom:
        - playing: {'wake_lock_size': 2}
        - paused: {'audio_state': 'paused'}
        - standby

calendar:
  - platform: ical
    url: !secret ical_url
    name: vacation

light:
  - platform: hyperion
    host: 127.0.0.1
    hdmi_priority: 240

shell_command:
  adb: "adb connect 192.168.1.123"
  # sudoers file required:
  # homeassistant ALL=(ALL) NOPASSWD: /bin/systemctl restart hyperion
  restart_hyperion: "sudo systemctl restart hyperion"

weather:
  - platform: openweathermap
    api_key: !secret weather_key

mobile_app:

# join app
notify:
  - platform: joaoapps_join
    api_key: !secret join_api_key
    device_id: !secret join_device_id
    name: pixel
joaoapps_join:
  - name: android
    device_id: group.android
    api_key: !secret join_api_key
