homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include conf/customize.yaml
  customize_glob:
    "scene.*_occupied":
      hidden: true
    "light.kitchen*":
      hidden: true
    "sensor.motion_sensor_*_2":
      icon: mdi:white-balance-sunny

config:

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: module

history:

recorder:
  purge_keep_days: 7
  exclude:
    domains:
      - automation
      - group
    entities:
      - sun.sun
      - sensor.date
      - binary_sensor.weekday
      - binary_sensor.dst
      - calendar.vacation

logbook:
  exclude:
    domains:
      - automation
      - group
      - input_number
    entities:
      - sensor.owm_current_cloud_coverage
      - sensor.owm_current_condition
      - sensor.owm_current_humidity
      - sensor.owm_current_pressure
      - sensor.owm_current_rain
      - sensor.owm_current_temperature
      - sensor.owm_current_weather_code
      - sensor.owm_forecast_cloud_coverage
      - sensor.owm_forecast_condition
      - sensor.owm_forecast_forecast
      - sensor.owm_forecast_humidity
      - sensor.owm_forecast_pressure
      - sensor.owm_forecast_rain
      - sensor.owm_forecast_temperature
      - sensor.owm_forecast_weather_code

http:

sun:

sensor:
  - platform: systemmonitor
    scan_interval: 30
    resources:
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
  - platform: time_date
    display_options:
      - date
  - platform: template
    sensors:
      bedroom_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_2_2", "battery_level") }}'
        unit_of_measurement: "%"
        friendly_name: "Bedroom sensor battery"
      bookcase_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_4_2", "battery_level") }}'
        unit_of_measurement: "%"
        friendly_name: "Bookcase sensor battery"
      living_room_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_10_2", "battery_level") }}'
        unit_of_measurement: "%"
        friendly_name: "Living room sensor battery"
      dining_room_battery:
        value_template: '{{ state_attr("sensor.motion_sensor_5_2", "battery_level") }}'
        unit_of_measurement: "%"
        friendly_name: "Dining room sensor battery"
      bed_triggered_1:
        value_template: '{{ states("sensor.bed_sensor_1") < states("input_number.bed_sensor_1") }}'
      bed_triggered_2:
        value_template: '{{ states("sensor.bed_sensor_2") < states("input_number.bed_sensor_2") }}'
      bed_triggered_3:
        value_template: '{{ states("sensor.bed_sensor_3") < states("input_number.bed_sensor_3") }}'
      bed_triggered_4:
        value_template: '{{ states("sensor.bed_sensor_4") < states("input_number.bed_sensor_4") }}'
      bed_occupied:
        value_template: '{% if [states("sensor.bed_triggered_1"), states("sensor.bed_triggered_2"), states("sensor.bed_triggered_3"), states("sensor.bed_triggered_4")]|select("equalto", "True")|list|length >= 2 %}on{% else %}off{% endif %}'
      asleep:
        value_template: >-
          {% if is_state("input_select.myhome_mode", "Asleep") %}
            on
          {% elif is_state("sensor.bed_occupied", "on") and (now() > today_at("05:00") and now() < today_at("09:30")) %}
            on
          {% else %}
            off
          {% endif %}
  - platform: filter
    name: "Bed sensor 1"
    entity_id: sensor.bed_sensor_16_2
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 1
      - filter: time_simple_moving_average
        window_size: "00:00:10"
  - platform: filter
    name: "Bed sensor 2"
    entity_id: sensor.bed_sensor_16_3
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 1
      - filter: time_simple_moving_average
        window_size: "00:00:10"
  - platform: filter
    name: "Bed sensor 3"
    entity_id: sensor.bed_sensor_16_4
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 1
      - filter: time_simple_moving_average
        window_size: "00:00:10"
  - platform: filter
    name: "Bed sensor 4"
    entity_id: sensor.bed_sensor_16_5
    filters:
      - filter: lowpass
        time_constant: 5
        precision: 1
      - filter: time_simple_moving_average
        window_size: "00:00:10"

binary_sensor:
  - platform: template
    sensors: !include_dir_merge_named binary_sensors/
  - platform: ping
    host: 192.168.1.131
    name: Xbox
    count: 2
    scan_interval: 30

hue:
  bridges:
    - host: 192.168.2.101
      filename: phue.conf

device_tracker:
- platform: !secret device_tracker_platform
  host: 192.168.1.1
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  track_new_devices: no

group:
  living_room:
    name: Living Room
    entities:
    - light.living_room_standing
    - light.tv_left
    - light.tv_right
    - light.hyperion
  bedroom:
    name: Bedroom
    entities:
    - light.lifx_white_656ad2
  kitchen:
    name: Kitchen
    entities:
    - light.rgbw_15_1
    - light.rgbw_15_2
  dining_room:
    name: Dining Room
    entities:
    - light.night_stand
    - light.dresser
  office:
    name: Office
    entities:
    - light.hall

automation: !include automations.yaml

script: !include scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.components: warning
    homeassistant.components.light: warning
    homeassistant.components.tomato.device_tracker: warning
    homeassistant.components.http: warning
    homeassistant.components.template.scene: warning
    mysensors: warning
    homeassistant.components.mysensors: warning

input_number:
  living_room_threshold:
    name: Living room threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: '%'
  kitchen_threshold:
    name: Kitchen threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: '%'
  bedroom_threshold:
    name: Bedroom threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: '%'
  dining_room_threshold:
    name: Dining room threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: '%'
  office_threshold:
    name: Office threshold
    min: 0
    max: 255
    mode: box
    unit_of_measurement: '%'
  bed_sensor_1:
    name: Bed sensor 1 threshold
    min: 0
    max: 100
    mode: box
    unit_of_measurement: '%'
  bed_sensor_2:
    name: Bed sensor 2 threshold
    min: 0
    max: 100
    mode: box
    unit_of_measurement: '%'
  bed_sensor_3:
    name: Bed sensor 3 threshold
    min: 0
    max: 80
    mode: box
    unit_of_measurement: '%'
  bed_sensor_4:
    name: Bed sensor 4 threshold
    min: 0
    max: 80
    mode: box
    unit_of_measurement: '%'

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Afternoon
      - Evening
      - Night
      - Asleep
    icon: mdi:format-list-bulleted
  media_mode:
    name: Media Mode
    options:
      - TV
      - Movie
      - Paused
      - Awake
      - Idle
      - "Off"
      - Disabled
    icon: mdi:format-list-bulleted
  current_theme:
    name: Theme
    options:
     - default
     - clear
     - clear-dark
     - amoled
     - blue_night
     - midnight
     - light
     - dark
     - "Google Light Theme"
     - "Google Dark Theme"
    initial: "Google Light Theme"
    icon: mdi:theme-light-dark

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:wrench
  myhome_active:
    name: Active
    icon: mdi:home-variant
  bedroom_occupied:
    name: Bedroom occupied
  kitchen_occupied:
    name: Kitchen occupied
  dining_room_occupied:
    name: Dining room occupied
  living_room_occupied:
    name: Living room occupied
  office_occupied:
    name: Office occupied
  room_bedroom:
    name: Bedroom
    icon: mdi:bed
  room_kitchen:
    name: Kitchen
    icon: mdi:silverware-spoon
  room_dining_room:
    name: Dining Room
    icon: mdi:table-chair
  room_living_room:
    name: Living Room
    icon: mdi:television-classic
  room_office:
    name: Office
    icon: mdi:briefcase
  autodark_theme:
    name: Auto-dark theme
    icon: mdi:theme-light-dark
  auto_living_room_standing:
    name: Auto update living room standing
  auto_living_room_tv:
    name: Auto update living room tv
  auto_kitchen:
    name: Auto update kitchen
  auto_bedroom:
    name: Auto update bedroom
  auto_dining_room:
    name: Auto update dining room
  auto_office:
    name: Auto update office

python_script:

shell_command:
  # sudoers file required on remote machine:
  # pi ALL=(ALL) NOPASSWD: /bin/systemctl restart hyperiond@pi.service
  restart_hyperion: "ssh pi@192.168.1.142 'sudo systemctl restart hyperiond@pi.service'"

mobile_app:

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

person:

panel_iframe:
  hyperion:
    title: 'Hyperion'
    url: 'http://192.168.1.142:8090'
    icon: mdi:led-variant-on

lifx:
  light:
    - broadcast: 192.168.1.228

system_health:

backup:

my:
