homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include conf/customize.yaml
  customize_glob:
    "scene.*_occupied":
      hidden: true
    "light.kitchen*":
      hidden: true
    "sensor.motion_sensor_*_2":
      icon: mdi:white-balance-sunny

myhome: !include conf/myhome.yaml

frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  themes: !include_dir_merge_named themes/

history:

recorder:
  purge_interval: 1
  purge_keep_days: 7

logbook:

http:

sun:

sensor:
  - platform: systemmonitor
    scan_interval: 30
    resources:
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use

binary_sensor:
  - platform: template
    sensors:
      dst:
        entity_id: sensor.date
        friendly_name: Daylight Savings
        value_template: "{% if now().dst() %}true{% else %}false{% endif %}"
      weekday:
        entity_id: sensor.date
        friendly_name: Weekday
        # 0-6 = Monday - Sunday
        value_template: "{% if now().weekday() < 5 %}true{% else %}false{% endif %}"

hue:
  bridges:
    - host: 192.168.1.124
      filename: phue.conf

device_tracker:
- platform: !secret device_tracker_platform
  host: 192.168.1.1
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  http_id: !secret device_tracker_http_id
  track_new_devices: no

mysensors:
  gateways:
    - device: '127.0.0.1'
      tcp_port: 5003
      persistence_file: '/home/homeassistant/hass-config/mysensors.json'
  persistence: true
  version: '1.5'

group:
  default_view:
    view: yes
    icon: mdi:home
    name: Home
    entities:
    - group.default_tv_scripts
    - group.default_living_room
    - group.default_bedroom
    - group.default_kitchen
    - group.default_hall
    - group.myhome
  light_view:
    view: yes
    icon: mdi:lightbulb-outline
    name: Lights
    entities:
    - group.living_room
    - group.bedroom
    - group.kitchen
    - group.hall
    - group.hue_lights
  media_view:
    view: yes
    icon: mdi:television-classic
    name: Media
    entities:
    - media_player.fire_tv
    - media_player.samsung_tv
    - switch.hdmi_0
    - switch.hdmi_8
    - group.tv_scripts
  sensors_view:
    view: yes
    icon: mdi:router-wireless
    name: Sensors
    entities:
    - group.living_room_sensors
    - group.bedroom_sensors
    - group.kitchen_sensors
    - group.hall_sensors
  presence_view:
    view: yes
    icon: mdi:account-multiple
    name: Presence
    entities:
    - group.rooms
    - group.presence
  automations_scripts:
    view: yes
    icon: mdi:wrench
    name: Setup
    entities:
    - group.scripts
    - group.system
    - group.theme
  living_room: &living_room
    name: Living Room
    entities:
    - light.living_room_standing
    - light.tv_left
    - light.tv_right
  default_living_room: *living_room
  living_room_sensors:
    name: Living Room Sensors
    entities:
    - binary_sensor.motion_sensor_4_1
    - sensor.motion_sensor_4_2
    - binary_sensor.motion_sensor_10_1
    - sensor.motion_sensor_10_2
  bedroom: &bedroom
    name: Bedroom
    entities:
    - light.night_stand
    - light.dresser
  default_bedroom: *bedroom
  bedroom_sensors:
    name: Bedroom Sensors
    entities:
    - binary_sensor.motion_sensor_2_1
    - sensor.motion_sensor_2_2
    - binary_sensor.bed_sensor_16_1
  kitchen: &kitchen
    name: Kitchen
    entities:
    - light.rgbw_15_1
    - light.rgbw_15_2
  default_kitchen: *kitchen
  kitchen_sensors:
    name: Kitchen Sensors
    entities:
    - binary_sensor.motion_sensor_1_1
    - sensor.motion_sensor_1_2
  hall: &hall
    name: Hall
    entities:
    - light.hall
  default_hall: *hall
  hall_sensors:
    name: Hall Sensors
    entities:
    - binary_sensor.motion_sensor_5_1
    - sensor.motion_sensor_5_2
  scripts:
    name: Scripts
    entities:
    - script.wakeup
    - script.snooze
    - script.bedtime
    - script.all_off
    - script.bedtime_now
    - script.reset_bed
  tv_scripts: &tv_scripts
    name: TV
    control: hidden
    entities:
    - script.firetv_home
    - script.watch_tv
    - script.watch_netflix
    - script.watch_espn
    - script.watch_fsgo
  default_tv_scripts:
    name: TV
    control: hidden
    entities:
    - input_text.tv_tiles
  theme:
    name: Theme
    entities:
    - input_boolean.autodark_theme
    - input_select.current_theme
  myhome:
    name: My Home
    entities:
    - input_boolean.myhome_active
    - input_select.myhome_mode
    - input_boolean.room_living_room
    - input_boolean.room_kitchen
    - input_boolean.room_hall
    - input_boolean.room_bedroom
  hue_lights:
    name: Hue Groups
    entities:
    - light.living_room
    - light.bedroom
  rooms:
    name: Rooms
    entities:
    - room.living_room
    - room.kitchen
    - room.hall
    - room.bedroom
  presence:
    name: Presence
    entities:
    - device_tracker.pixel
    - device_tracker.rfid_sensor_12_1
  system:
    name: System
    entities:
    - sensor.memory_use
    - sensor.memory_free
    - sensor.swap_use
    - sensor.swap_free
    - sensor.load_1m
    - sensor.load_5m
    - sensor.load_15m
    - sensor.processor_use

automation: !include_dir_merge_list automations/

scene: !include_dir_merge_list scenes/

script: !include_dir_merge_named scripts/

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.device_tracker.tomato: warning
    homeassistant.components.device_tracker.nmap_tracker: warning
    homeassistant.components.http: warning
    #mysensors: debug
    homeassistant.components.sensor.mysensors: debug
    custom_components.myhome: debug
    #homeassistant.helpers.script: info

updater:
  reporting: no

input_text:
  tv_tiles:
    name: dummy

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Afternoon
      - Evening
      - Night
      - Asleep
    initial: Reset
    icon: mdi:format-list-bulleted
  current_theme:
    name: Theme
    options:
     - default
     - midnight
    initial: default
    icon: mdi:theme-light-dark


input_boolean:
  myhome_active:
    name: Active
    initial: off
    icon: mdi:home-variant
  room_bedroom:
    name: Bedroom
    initial: on
    icon: mdi:hotel
  room_kitchen:
    name: Kitchen
    initial: on
    icon: mdi:silverware-spoon
  room_hall:
    name: Hall
    initial: on
    icon: mdi:glassdoor
  room_living_room:
    name: Living Room
    initial: on
    icon: mdi:television-classic
  autodark_theme:
    name: Auto-dark theme
    initial: on
    icon: mdi:theme-light-dark

python_script:

hdmi_cec:
  devices:
    TV: 0.0.0.0
    Xbox One: 2.0.0.0
    Fire TV: 1.0.0.0
    Pi: 3.0.0.0

media_player:
  - platform: firetv
    name: Fire TV
    host: 192.168.1.129
    adbkey: "/home/homeassistant/hass-config/android/adbkey"
    scan_interval: 4
  - platform: samsungtv
    name: Samsung TV
    host: 192.168.1.134
    port: 8001

calendar:
  - platform: ical
    url: !secret ical_url
    name: vacation
