homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: 34.2437413
  longitude: -88.7026712

http:

sun:

light:
  platform: hue

device_tracker:
  platform: nmap_tracker
  hosts: 192.168.1.105
  home_interval: 10

device_sun_light_trigger:
  light_group: group.living_room
  light_profile: relax


lighthub:
  port: /dev/ttyUSB0

group:
  living_room:
    - light.Living_room_standing
    - light.Living_room_table
  bedroom:
    - light.Bedroom
  kitchen:
    - light.Kitchen_1
    - light.Kitchen_2
    - light.Kitchen_3
  hall:
    - light.Hall
    - light.Hall_2

automation:
  alias: Hall light
  platform: event
  event_type: lighthub_changed
  event_data:
    nodeid: 2
    gesture: 1
    electrode: 4
    repeat: 0
  execute_service: lighthub.toggle
  service_entity_id: group.hall

automation 2:
  alias: Dim Hall light
  platform: event
  event_type: lighthub_changed
  event_data:
    nodeid: 2
    gesture: 3
    electrode: 0
    repeat: 1
  execute_service: lighthub.dim
  service_entity_id: group.hall

automation 3:
  alias: Dim Hall light
  platform: event
  event_type: lighthub_changed
  event_data:
    nodeid: 2
    gesture: 1
    electrode: 0
    repeat: 0
  execute_service: lighthub.dim
  service_entity_id: group.hall

automation 4:
  alias: Brighten Hall light
  platform: event
  event_type: lighthub_changed
  event_data:
    nodeid: 2
    gesture: 4
    electrode: 2
    repeat: 1
  execute_service: lighthub.brighten
  service_entity_id: group.hall

automation 5:
  alias: Brighten Hall light
  platform: event
  event_type: lighthub_changed
  event_data:
    nodeid: 2
    gesture: 1
    electrode: 2
    repeat: 0
  execute_service: lighthub.brighten
  service_entity_id: group.hall

