homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !include conf/latitude.yaml
  longitude: !include conf/longitude.yaml
  temperature_unit: F
  time_zone: America/Chicago
  customize:
    group.living_room:
      friendly_name: Living Room
    sensor.motion_sensor_11:
      friendly_name: Kitchen Motion
    sensor.motion_sensor_12:
      friendly_name: Kitchen Light
    sensor.motion_sensor_21:
      friendly_name: Bedroom Motion
    sensor.motion_sensor_22:
      friendly_name: Bedroom Light
    sensor.motion_sensor_41:
      friendly_name: Bookcase Motion
    sensor.motion_sensor_42:
      friendly_name: Bookcase Light
    sensor.motion_sensor_51:
      friendly_name: Front Door Motion
    sensor.motion_sensor_52:
      friendly_name: Front Door Light
    sensor.motion_sensor_101:
      friendly_name: Living Room Motion
    sensor.motion_sensor_102:
      friendly_name: Living Room Light

myhome: !include conf/myhome.yaml

history:

http:

sun:

light:
  platform: hue

device_tracker: !include conf/device_tracker.yaml

device_sun_light_trigger:
  light_group: group.living_room
  light_profile: relax

sensor:
  - platform: mysensors
    gateway: serial
    port: /dev/ttyUSB0
    debug: True

group:
  living_room:
    - light.Living_room_standing
    - light.Living_room_table
  bedroom:
    - light.Bedroom
    - light.Bedroom_2
  kitchen:
    - light.Kitchen_1
    - light.Kitchen_2
    - light.Kitchen_3
  hall:
    - light.Hall
    - light.Hall_2

automation:
  - platform: state
    state_entity_id: group.all_devices
    state_to: not_home
    execute_service: light.turn_off
    service_entity_id: group.all_lights

scene: !include conf/scenes.yaml

script: !include conf/scripts.yaml
