homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !include conf/latitude.yaml
  longitude: !include conf/longitude.yaml
  temperature_unit: F
  time_zone: America/Chicago
  customize:
    group.living_room:
      friendly_name: Living Room
    group.myhome:
      friendly_name: My Home
    binary_sensor.motion_sensor_11:
      friendly_name: Kitchen Motion
    sensor.motion_sensor_12:
      friendly_name: Kitchen Light
    binary_sensor.motion_sensor_21:
      friendly_name: Bedroom Motion
    sensor.motion_sensor_22:
      friendly_name: Bedroom Light
    binary_sensor.motion_sensor_41:
      friendly_name: Bookcase Motion
    sensor.motion_sensor_42:
      friendly_name: Bookcase Light
    binary_sensor.motion_sensor_51:
      friendly_name: Front Door Motion
    sensor.motion_sensor_52:
      friendly_name: Front Door Light
    binary_sensor.motion_sensor_101:
      friendly_name: Living Room Motion
    sensor.motion_sensor_102:
      friendly_name: Living Room Light
    sensor.rfid_sensor_121:
      friendly_name: RFID Sensor
      hidden: true
    room.living_room:
      friendly_name: 'Living Room'

myhome: !include conf/myhome.yaml

history:

logbook:

http:

sun:

light:
  platform: hue

device_tracker: !include conf/device_tracker.yaml

media_player:
  platform: cast
  host: 192.168.1.115

mysensors:
  gateways:
    - port: '/dev/ttyUSB0'
      persistence_file: '/srv/hass-config/mysensors.json'
  debug: true
  persistence: true
  version: '1.5'

switch:
  - platform: rest
    resource: http://192.168.1.148/pwr
    name: "Chromecast"
    body_on: "state=on"
    body_off: "state=off"

group:
  living_room:
    - light.Living_room_standing
    - light.Living_room_table
    - binary_sensor.motion_sensor_41
    - sensor.motion_sensor_42
    - binary_sensor.motion_sensor_101
    - sensor.motion_sensor_102
  bedroom:
    - light.Bedroom
    - light.Bedroom_2
    - binary_sensor.motion_sensor_21
    - sensor.motion_sensor_22
  kitchen:
    - light.Kitchen_1
    - light.Kitchen_2
    - light.Kitchen_3
    - binary_sensor.motion_sensor_11
    - sensor.motion_sensor_12
  hall:
    - light.Hall
    - light.Hall_2
    - binary_sensor.motion_sensor_51
    - sensor.motion_sensor_52
  scripts:
    - script.wakeup
    - script.snooze
    - script.bedtime
    - script.all_off
    - script.bedtime_now
  myhome:
    - myhome.active
    - input_select.myhome_mode
    - room.living_room
    - room.kitchen
    - room.hall
    - room.bedroom
  media:
    - media_player.living_room
    - switch.chromecast

automation: !include conf/automation.yaml

scene: !include conf/scenes.yaml

script: !include conf/scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.device_tracker.tomato.Tomato: warning
    homeassistant.components.http: warning
    mysensors.mysensors: debug
    homeassistant.components.sensor.mysensors: debug
    custom_components.myhome: debug

updater:

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Evening
      - Night
      - Asleep
    initial: Reset
    icon: mdi:format-list-bulleted
