homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include conf/customize.yaml
  customize_glob:
    scene.*_occupied:
      hidden: true
    light.kitchen*:
      hidden: true

myhome: !include conf/myhome.yaml

frontend:

history:

recorder:
  purge_days: 7

logbook:

http:

sun:

sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

light:
  platform: hue
  host: 192.168.1.124

device_tracker:
- platform: !secret device_tracker_platform
  host: 192.168.1.1
  username: !secret device_tracker_username
  password: !secret device_tracker_password
  http_id: !secret device_tracker_http_id
  track_new_devices: no

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: '/srv/hass-config/mysensors.json'
  persistence: true
  version: '1.5'

group:
  living_room:
    name: Living Room
    entities:
    - light.living_room_standing
    - light.tv_left
    - light.tv_right
    - binary_sensor.motion_sensor_4_1
    - sensor.motion_sensor_4_2
    - binary_sensor.motion_sensor_10_1
    - sensor.motion_sensor_10_2
  bedroom:
    name: Bedroom
    entities:
    - light.night_stand
    - light.dresser
    - binary_sensor.motion_sensor_2_1
    - sensor.motion_sensor_2_2
    - binary_sensor.bed_sensor_16_1
  kitchen:
    name: Kitchen
    entities:
    - binary_sensor.motion_sensor_1_1
    - sensor.motion_sensor_1_2
    - light.rgbw_15_1
    - light.rgbw_15_2
  hall:
    name: Hall
    entities:
    - binary_sensor.motion_sensor_5_1
    - sensor.motion_sensor_5_2
    - light.hall
  scripts:
    name: Scripts
    entities:
    - script.wakeup
    - script.snooze
    - script.bedtime
    - script.all_off
    - script.bedtime_now
  myhome:
    name: My Home
    entities:
    - myhome.active
    - input_select.myhome_mode
    - room.living_room
    - room.kitchen
    - room.hall
    - room.bedroom
    - light.living_room
    - light.bedroom
  weather:
    name: Weather
    entities:
    - sensor.yweather_condition
    - sensor.yweather_current
    - sensor.yweather_humidity
    - sensor.yweather_pressure
    - sensor.yweather_temperature
    - sensor.yweather_temperature_max
    - sensor.yweather_temperature_min
    - sensor.yweather_visibility
    - sensor.yweather_wind_speed
    - sun.sun
  presence:
    name: Presence
    entities:
    - device_tracker.pixel
    - device_tracker.rfid_sensor_12_1

automation: !include conf/automation.yaml

scene: !include conf/scenes.yaml

script: !include conf/scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.device_tracker.tomato.Tomato: warning
    homeassistant.components.device_tracker.nmap_tracker: warning
    homeassistant.components.http: warning
    mysensors.mysensors: debug
    homeassistant.components.sensor.mysensors: debug
    custom_components.myhome: debug

updater:
  reporting: no

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Afternoon
      - Evening
      - Night
      - Asleep
    initial: Reset
    icon: mdi:format-list-bulleted
