homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !include conf/latitude.yaml
  longitude: !include conf/longitude.yaml
  temperature_unit: F
  time_zone: America/Chicago
  customize:
    group.living_room:
      friendly_name: Living Room
    sensor.motion_sensor_11:
      friendly_name: Kitchen Motion
    sensor.motion_sensor_12:
      friendly_name: Kitchen Light
    sensor.motion_sensor_21:
      friendly_name: Bedroom Motion
    sensor.motion_sensor_22:
      friendly_name: Bedroom Light
    sensor.motion_sensor_41:
      friendly_name: Bookcase Motion
    sensor.motion_sensor_42:
      friendly_name: Bookcase Light
    sensor.motion_sensor_51:
      friendly_name: Front Door Motion
    sensor.motion_sensor_52:
      friendly_name: Front Door Light
    sensor.motion_sensor_101:
      friendly_name: Living Room Motion
    sensor.motion_sensor_102:
      friendly_name: Living Room Light
    myhome.active:
      icon: 'mdi:home-variant'
    room.bedroom:
      icon: 'mdi:home-variant'
    room.kitchen:
      icon: 'mdi:home-variant'
    room.living_room:
      friendly_name: 'Living Room'
      icon: 'mdi:home-variant'
    room.hall:
      icon: 'mdi:home-variant'
    scene.living_room_morning_occupied:
      hidden: True
    scene.living_room_day_occupied:
      hidden: True
    scene.living_room_afternoon_occupied:
      hidden: True
    scene.living_room_evening_occupied:
      hidden: True
    scene.living_room_night_occupied:
      hidden: True
    scene.bedroom_morning_occupied:
      hidden: True
    scene.bedroom_day_occupied:
      hidden: True
    scene.bedroom_afternoon_occupied:
      hidden: True
    scene.bedroom_evening_occupied:
      hidden: True
    scene.bedroom_night_occupied:
      hidden: True
    scene.kitchen_morning_occupied:
      hidden: True
    scene.kitchen_day_occupied:
      hidden: True
    scene.kitchen_afternoon_occupied:
      hidden: True
    scene.kitchen_evening_occupied:
      hidden: True
    scene.kitchen_night_occupied:
      hidden: True
    scene.hall_morning_occupied:
      hidden: True
    scene.hall_day_occupied:
      hidden: True
    scene.hall_afternoon_occupied:
      hidden: True
    scene.hall_evening_occupied:
      hidden: True
    scene.hall_night_occupied:
      hidden: True
    scene.living_room_morning_not_occupied:
      hidden: True
    scene.living_room_day_not_occupied:
      hidden: True
    scene.living_room_afternoon_not_occupied:
      hidden: True
    scene.living_room_evening_not_occupied:
      hidden: True
    scene.living_room_night_not_occupied:
      hidden: True
    scene.bedroom_morning_not_occupied:
      hidden: True
    scene.bedroom_day_not_occupied:
      hidden: True
    scene.bedroom_afternoon_not_occupied:
      hidden: True
    scene.bedroom_evening_not_occupied:
      hidden: True
    scene.bedroom_night_not_occupied:
      hidden: True
    scene.kitchen_morning_not_occupied:
      hidden: True
    scene.kitchen_day_not_occupied:
      hidden: True
    scene.kitchen_afternoon_not_occupied:
      hidden: True
    scene.kitchen_evening_not_occupied:
      hidden: True
    scene.kitchen_night_not_occupied:
      hidden: True
    scene.hall_morning_not_occupied:
      hidden: True
    scene.hall_day_not_occupied:
      hidden: True
    scene.hall_afternoon_not_occupied:
      hidden: True
    scene.hall_evening_not_occupied:
      hidden: True
    scene.hall_night_not_occupied:
      hidden: True

myhome: !include conf/myhome.yaml

history:

logbook:

http:

sun:

light:
  platform: hue

device_tracker: !include conf/device_tracker.yaml

media_player:
  platform: cast
  host: 192.168.1.115

sensor:
  - platform: mysensors
    gateway: serial
    port: /dev/ttyUSB0
    debug: True
    persistence_file: mysensors.json

group:
  living_room:
    - light.Living_room_standing
    - light.Living_room_table
    - sensor.motion_sensor_41
    - sensor.motion_sensor_42
    - sensor.motion_sensor_101
    - sensor.motion_sensor_102
    - room.living_room
  bedroom:
    - light.Bedroom
    - light.Bedroom_2
    - sensor.motion_sensor_21
    - sensor.motion_sensor_22
    - room.bedroom
  kitchen:
    - light.Kitchen_1
    - light.Kitchen_2
    - light.Kitchen_3
    - sensor.motion_sensor_11
    - sensor.motion_sensor_12
    - room.kitchen
  hall:
    - light.Hall
    - light.Hall_2
    - room.hall
    - sensor.motion_sensor_51
    - sensor.motion_sensor_52
  scripts:
    - script.wakeup
    - script.snooze
    - script.bedtime

automation: !include conf/automation.yaml

scene: !include conf/scenes.yaml

script: !include conf/scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.device_tracker.tomato.Tomato: warning
    homeassistant.components.http: warning
    mysensors.mysensors: debug
    homeassistant.components.sensor.mysensors: debug
    custom_components.myhome: debug
