homeassistant:
  # Location required to calculate the time the sun rises and sets
  latitude: !include conf/latitude.yaml
  longitude: !include conf/longitude.yaml
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include conf/customize.yaml

myhome: !include conf/myhome.yaml

frontend:

history:

recorder:
  purge_days: 7

logbook:

http:

sun:

sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

light:
  platform: hue
  host: 192.168.1.124

device_tracker: !include conf/device_tracker.yaml

media_player:
  - platform: cast
    host: 192.168.1.115

mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: '/srv/hass-config/mysensors.json'
  debug: true
  persistence: true
  version: '1.5'

group:
  living_room:
    - light.Living_room_standing
    - light.tv_left
    - light.tv_right
    - binary_sensor.motion_sensor_4_1
    - sensor.motion_sensor_4_2
    - binary_sensor.motion_sensor_10_1
    - sensor.motion_sensor_10_2
  bedroom:
    - light.Bedroom
    - light.Bedroom_2
    - binary_sensor.motion_sensor_2_1
    - sensor.motion_sensor_2_2
  kitchen:
    - binary_sensor.motion_sensor_1_1
    - sensor.motion_sensor_1_2
    - light.rgbw_15_1
    - light.rgbw_15_2
  hall:
    - light.Hall
    - light.Hall_2
    - binary_sensor.motion_sensor_5_1
    - sensor.motion_sensor_5_2
  scripts:
    - script.wakeup
    - script.snooze
    - script.bedtime
    - script.all_off
    - script.bedtime_now
  myhome:
    - myhome.active
    - input_select.myhome_mode
    - room.living_room
    - room.kitchen
    - room.hall
    - room.bedroom
  media:
    - media_player.living_room
    - switch.chromecast

automation: !include conf/automation.yaml

scene: !include conf/scenes.yaml

script: !include conf/scripts.yaml

logger:
  default: warning
  logs:
    homeassistant.components: info
    homeassistant.components.light: warning
    homeassistant.components.device_tracker.tomato.Tomato: warning
    homeassistant.components.device_tracker.nmap_tracker: warning
    homeassistant.components.http: warning
    mysensors.mysensors: debug
    homeassistant.components.sensor.mysensors: debug
    custom_components.myhome: debug

updater:

input_select:
  myhome_mode:
    name: Mode
    options:
      - Reset
      - Morning
      - Day
      - Afternoon
      - Evening
      - Night
      - Asleep
    initial: Reset
    icon: mdi:format-list-bulleted
