title: My Home
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.3
    type: module
  - url: /local/theme-maker.js?v=0.1
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /local/vertical-style-card.js?v=0.1
    type: js
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module
views:
  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/media.yaml
  - !include lovelace/sensors.yaml
  - !include lovelace/system.yaml
