title: My Home
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.3
    type: module
  - url: /local/theme-maker.js?v=0.1
    type: js
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
  - url: /local/vertical-style-card.js?v=0.1
    type: js
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module

button_card_templates:
  large:
    color: var(--secondary-text-color)
    show_state: true
    show_name: false
    show_label: true
    show_entity_picture: true
    aspect_ratio: 4/3
    styles:
      label:
        - font-size: 0.95rem
        - color: var(--secondary-text-color)
      state:
        - text-transform: capitalize
      entity_picture:
        - border-radius: 50%
        - margin-bottom: "-4px"
    tap_action:
      action: more-info
  large_toggle:
    template: large
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    state:
      - value: "on"
        id: "on"
        color: var(--light-primary-color)
  small:
    color: var(--secondary-text-color)
    show_state: false
    show_name: false
    show_label: true
    aspect_ratio: 4/3
    styles:
      label:
        - font-size: 0.95rem
        - color: var(--secondary-text-color)
    tap_action:
      action: more-info
  small_presence:
    template: small
    state:
      - value: "occupied"
        color: var(--light-primary-color)
    tap_action:
      action: more-info
  small_toggle:
    template: small
    state:
      - value: "on"
        id: "on"
        color: var(--light-primary-color)
      - value: "off"
        id: "off"
    tap_action:
      action: toggle
    hold_action:
      action: more-info
  small_toggle_icon:
    template: small_toggle
    state:
      - id: "on"
        icon: mdi:checkbox-marked-circle
      - id: "off"
        icon: mdi:checkbox-blank-circle-outline

views:
  - title: Home
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: vertical-stack
            cards:
              #- type: custom:theme-maker
              - type: conditional
                conditions:
                  - entity: room.living_room
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Living Room
                  show_header_toggle: true
                  entities:
                    - light.living_room_standing
                    - light.tv_left
                    - light.tv_right
              - type: conditional
                conditions:
                  - entity: room.bedroom
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Bedroom
                  show_header_toggle: true
                  entities:
                    - light.night_stand
                    - light.dresser
              - type: conditional
                conditions:
                  - entity: room.kitchen
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Kitchen
                  show_header_toggle: true
                  entities:
                    - light.rgbw_15_1
                    - light.rgbw_15_2
              - type: conditional
                conditions:
                  - entity: room.hall
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Hall
                  show_header_toggle: true
                  entities:
                    - light.hall
          - type: vertical-stack
            cards:
            - type: custom:vertical-style-card
              title: Media
              style:
                font_size: 22px
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      entity: input_select.media_mode
                      template: large
                      label: "Mode"
                      state:
                        - value: "Disabled"
                          icon: mdi:filmstrip-off
                        - value: "Off"
                          icon: mdi:power-off
                        - value: "Idle"
                          icon: mdi:sleep
                        - value: "Awake"
                          icon: mdi:apps
                          color: var(--light-primary-color)
                        - value: "Paused"
                          icon: mdi:pause
                          color: var(--light-primary-color)
                        - value: "TV"
                          icon: mdi:youtube-tv
                          color: var(--light-primary-color)
                        - value: "Movie"
                          icon: mdi:filmstrip
                          color: var(--light-primary-color)
                    - type: "custom:button-card"
                      entity: light.hyperion
                      template: large_toggle
                      label: "Backlight"
                      tap_action:
                        action: call-service
                        service: light.toggle
                        service_data:
                          entity_id: light.hyperion
                          effect: HDMI
            - type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      template: large_toggle
                      entity: input_boolean.myhome_active
                      label: "Home Active"
                    - type: "custom:button-card"
                      template: large
                      entity: input_select.myhome_mode
                      label: "Home Mode"
                      tap_action:
                        action: more-info
            - type: custom:weather-card
              entity: weather.openweathermap
            - type: custom:vertical-style-card
              title: Presence
              style:
                font_size: 18px
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      template: small_presence
                      entity: room.living_room
                      label: "Living Room"
                    - type: "custom:button-card"
                      template: small_presence
                      entity: room.bedroom
                      label: "Bedroom"
                    - type: "custom:button-card"
                      template: small_presence
                      entity: room.kitchen
                      label: "Kitchen"
                    - type: "custom:button-card"
                      template: small_presence
                      entity: room.hall
                      label: "Hall"
            - type: custom:vertical-style-card
              title: Auto update
              style:
                font_size: 18px
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      template: small_toggle_icon
                      entity: input_boolean.auto_living_room_tv
                      label: "TV"
                    - type: "custom:button-card"
                      template: small_toggle_icon
                      entity: input_boolean.auto_living_room_standing
                      label: "Living Room"
                    - type: "custom:button-card"
                      template: small_toggle_icon
                      entity: input_boolean.auto_bedroom
                      label: "Bedroom"
                    - type: "custom:button-card"
                      template: small_toggle_icon
                      entity: input_boolean.auto_kitchen
                      label: "Kitchen"
                    - type: "custom:button-card"
                      template: small_toggle_icon
                      entity: input_boolean.auto_hall
                      label: "Hall"
            - type: custom:vertical-style-card
              title: Rooms
              style:
                font_size: 18px
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      template: small_toggle
                      entity: input_boolean.room_living_room
                      label: "Living Room"
                    - type: "custom:button-card"
                      template: small_toggle
                      entity: input_boolean.room_bedroom
                      label: "Bedroom"
                    - type: "custom:button-card"
                      template: small_toggle
                      entity: input_boolean.room_kitchen
                      label: "Kitchen"
                    - type: "custom:button-card"
                      template: small_toggle
                      entity: input_boolean.room_hall
                      label: "Hall"
            - type: custom:vertical-style-card
              title: Devices
              style:
                font_size: 22px
              cards:
                - type: horizontal-stack
                  cards:
                    - type: "custom:button-card"
                      template: large
                      entity: device_tracker.pixel
                      label: "Phone"
                    - type: "custom:button-card"
                      template: large
                      entity: device_tracker.rfid_sensor_12_1
                      label: "Wallet"
            - type: custom:compact-custom-header
              main_config: true

  - title: Lights
    icon: mdi:lightbulb-outline
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: entities
            title: Living Room
            entities:
              - light.living_room_standing
              - light.tv_left
              - light.tv_right
              - light.hyperion
          - type: entities
            title: Bedroom
            entities:
              - light.night_stand
              - light.dresser
          - type: entities
            title: Kitchen
            entities:
              - light.rgbw_15_1
              - light.rgbw_15_2
          - type: entities
            title: Hall
            entities:
              - light.hall
          - type: custom:compact-custom-header

  - title: Media
    icon: mdi:television-classic
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: media-control
            entity: media_player.android_tv
          - type: media-control
            entity: media_player.samsung_tv
          - type: glance
            title: My Media
            entities:
              - input_select.media_mode
          - type: custom:compact-custom-header

  - title: Sensors
    icon: mdi:router-wireless
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: entities
            title: Sensors
            entities:
              - type: section
                label: Living Room
              - binary_sensor.motion_sensor_4_1
              - binary_sensor.motion_sensor_10_1
              - type: section
                label: Bedroom
              - binary_sensor.motion_sensor_2_1
              - binary_sensor.bed_sensor_16_1
              - type: section
                label: Kitchen
              - binary_sensor.motion_sensor_1_1
              - type: section
                label: Hall
              - binary_sensor.motion_sensor_5_1
              - type: section
                label: Other
              - entity: binary_sensor.weekday
                name: Weekday
              - entity: calendar.vacation
                name: Vacation
              - entity: binary_sensor.dst
                name: Daylight Savings
              - sun.sun
          - type: vertical-stack
            cards:
              - type: custom:mini-graph-card
                name: Living Room
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                line_width: 1
                entities:
                  - entity: sensor.living_room_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_10_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Bookcase
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                line_width: 1
                entities:
                  - entity: sensor.bookcase_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_4_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Bedroom
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                line_width: 1
                entities:
                  - entity: sensor.bedroom_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_2_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Kitchen
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                line_width: 1
                entities:
                  - entity: sensor.kitchen_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_10_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Hall
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                line_width: 1
                entities:
                  - entity: sensor.hall_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_5_2
                    name: SENSOR
          - type: custom:compact-custom-header

  - title: System
    icon: mdi:wrench
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                title: CPU usage
                entity: sensor.processor_use
              - type: gauge
                title: Load 1m
                entity: sensor.load_1m
          - type: horizontal-stack
            cards:
              - type: gauge
                title: Load 5m
                entity: sensor.load_5m
              - type: gauge
                title: Load 15m
                entity: sensor.load_15m
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                line_width: 1
                entities:
                  - sensor.memory_use
              - type: custom:mini-graph-card
                line_width: 1
                entities:
                  - sensor.swap_use
          - type: entities
            title: Scripts
            entities:
              - script.all_off
              - script.bedtime
              - script.bedtime_now
              - script.reset_bed
              - script.wakeup
              - script.snooze
          - type: entities
            title: Theme
            entities:
              - input_boolean.autodark_theme
              - input_select.current_theme
          - type: custom:tracker-card
          - type: custom:compact-custom-header
