title: My Home
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/thomasloven/card-tools.js?track=true
    type: js
  - url: /customcards/github/thomasloven/layout-card.js?track=true
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.3.3
    type: module
  - url: /local/theme-maker.js?v=0.1
    type: js
views:
  - title: Home
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          #- type: custom:theme-maker
          - type: vertical-stack
            cards:
              - type: conditional
                conditions:
                  - entity: room.living_room
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Living Room
                  show_header_toggle: true
                  entities:
                    - light.living_room_standing
                    - light.tv_left
                    - light.tv_right
              - type: conditional
                conditions:
                  - entity: room.bedroom
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Bedroom
                  show_header_toggle: true
                  entities:
                    - light.night_stand
                    - light.dresser
              - type: conditional
                conditions:
                  - entity: room.kitchen
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Kitchen
                  show_header_toggle: true
                  entities:
                    - light.rgbw_15_1
                    - light.rgbw_15_2
              - type: conditional
                conditions:
                  - entity: room.hall
                    state_not: "not_occupied"
                card:
                  type: entities
                  title: Hall
                  show_header_toggle: true
                  entities:
                    - light.hall
          - type: vertical-stack
            cards:
              - type: glance
                title: My Home
                columns: 4
                entities:
                  - entity: input_boolean.myhome_active
                    tap_action:
                      action: toggle
                  - input_select.myhome_mode
                  - entity: device_tracker.pixel
                    name: Phone
                  - entity: device_tracker.rfid_sensor_12_1
                    name: Wallet
                  - entity: input_boolean.room_living_room
                    tap_action:
                      action: toggle
                  - entity: input_boolean.room_bedroom
                    tap_action:
                      action: toggle
                  - entity: input_boolean.room_kitchen
                    tap_action:
                      action: toggle
                  - entity: input_boolean.room_hall
                    tap_action:
                      action: toggle
              - type: glance
                title: My Media
                columns: 3
                entities:
                  - input_select.media_mode
                  - entity: light.hyperion
                    name: Backlight
              - type: glance
                title: Presence
                show_state: false
                columns: 4
                entities:
                  - entity: room.living_room
                    name: Living Room
                  - entity: room.bedroom
                    name: Bedroom
                  - entity: room.kitchen
                    name: Kitchen
                  - entity: room.hall
                    name: Hall

  - title: Lights
    icon: mdi:lightbulb-outline
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
           - type: entities
             title: Living Room
             entities:
               - light.living_room_standing
               - light.tv_left
               - light.tv_right
               - light.hyperion
           - type: entities
             title: Bedroom
             entities:
               - light.night_stand
               - light.dresser
           - type: entities
             title: Kitchen
             entities:
               - light.rgbw_15_1
               - light.rgbw_15_2
           - type: entities
             title: Hall
             entities:
               - light.hall

  - title: Media
    icon: mdi:television-classic
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: media-control
            entity: media_player.android_tv
          - type: media-control
            entity: media_player.samsung_tv
          - type: glance
            title: My Media
            entities:
              - input_select.media_mode

  - title: Sensors
    icon: mdi:router-wireless
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: entities
            title: Sensors
            entities:
              - type: section
                label: Living Room
              - binary_sensor.motion_sensor_4_1
              - binary_sensor.motion_sensor_10_1
              - binary_sensor.dark_living_room
              - input_boolean.dark_living_room
              - type: section
                label: Bedroom
              - binary_sensor.motion_sensor_2_1
              - binary_sensor.bed_sensor_16_1
              - binary_sensor.dark_bedroom
              - input_boolean.dark_bedroom
              - type: section
                label: Kitchen
              - binary_sensor.motion_sensor_1_1
              - binary_sensor.dark_kitchen
              - input_boolean.dark_kitchen
              - type: section
                label: Hall
              - binary_sensor.motion_sensor_5_1
              - binary_sensor.dark_hall
              - input_boolean.dark_hall
              - type: section
                label: Other
              - entity: binary_sensor.weekday
                name: Weekday
              - entity: calendar.vacation
                name: Vacation
              - entity: binary_sensor.dst
                name: Daylight Savings
              - sun.sun
          - type: vertical-stack
            cards:
              - type: custom:mini-graph-card
                name: Living Room
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                entities:
                  - entity: sensor.living_room_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_10_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Bookcase
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                entities:
                  - entity: sensor.bookcase_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_4_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Bedroom
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                entities:
                  - entity: sensor.bedroom_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_2_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Kitchen
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                entities:
                  - entity: sensor.kitchen_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_10_2
                    name: SENSOR
              - type: custom:mini-graph-card
                name: Hall
                points_per_hour: 6
                hours_to_show: 16
                show:
                  points: false
                height: 175
                entities:
                  - entity: sensor.hall_threshold
                    name: THRESHOLD
                  - entity: sensor.motion_sensor_5_2
                    name: SENSOR

  - title: System
    icon: mdi:wrench
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 2
        max_width: [42%, 42%]
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                title: CPU usage
                entity: sensor.processor_use
              - type: gauge
                title: Load 1m
                entity: sensor.load_1m
          - type: horizontal-stack
            cards:
              - type: gauge
                title: Load 5m
                entity: sensor.load_5m
              - type: gauge
                title: Load 15m
                entity: sensor.load_15m
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.memory_use
              - type: custom:mini-graph-card
                entities:
                  - sensor.swap_use
          - type: entities
            title: Scripts
            entities:
              - script.all_off
              - script.bedtime
              - script.bedtime_now
              - script.reset_bed
              - script.wakeup
              - script.snooze
          - type: entities
            title: Theme
            entities:
              - input_boolean.autodark_theme
              - input_select.current_theme
          - type: custom:tracker-card
