blueprint:
  name: Auto-Light brightness
  description: Controls the brightness of a light based on several factors
  domain: automation
  input:
    lights:
      name: Lights
      description: The lights to control
      selector:
        entity:
          domain: light
          multiple: true
    toggle_switch:
      name: Toggle switch
      description: Turns automatic control of the lights on/off
      selector:
        entity:
          domain: input_boolean
          multiple: true
    light_sensor:
      name: Light sensor
      description: Light level sensor
      selector:
        entity:
          domain: sensor
    light_threshold:
      name: Light threshold
      description: Light threshold number
      selector:
        entity:
          domain: input_number
    minimum_brightness:
      name: Minimum brightness
      default: 0
      selector:
        number:
          min: 0
          max: 255
          mode: box
    hysteresis:
      name: Hysteresis
      description: Prevent constant toggling when near the threshold values.
      default: 3
      selector:
        number:
          min: 0
          max: 100
          mode: box
    presence_sensor:
      name: Presence sensor
      description: Room presence sensor. Lights are only updated in occupied rooms.
      selector:
        entity:
          domain: input_boolean
    disable_when_on:
      name: Disable when on
      description: Disable auto-updating when these entities are on.
      default: ""
      selector:
        entity:
          multiple: true
    brightness_override_entity:
      name: Brightness override entity
      description: Optional entity that can override brightness values based on state
      default: ""
      selector:
        entity:
    brightness_override_states:
      name: Brightness override states
      description: Mapping of states to override brightness values
      default: ""
      selector:
        object:
    transition:
      name: Brightness transition time
      default: 0
      selector:
        number:
          min: 0
          max: 300
    unoccupied_duration:
      name: Unoccupied duration
      description: Number of minutes to leave lights on in an unoccupied room before turning off
      default: 5
      selector:
        number:
          min: 0
          max: 30
    time_pattern_minutes:
      name: Time pattern minutes
      description: "Pattern for when to run this automation (ex: /1 every minute)"
      default: "/1"
    time_pattern_seconds:
      name: Time pattern seconds
      description: "Pattern for when to run this automation (ex: /1 every second)"
      default: "0"

mode: single
max_exceeded: silent

variables:
  brightness_override_entity: !input brightness_override_entity
  brightness_override_states: !input brightness_override_states
  light_sensor: !input light_sensor
  light_threshold: !input light_threshold
  lights: !input lights
  minimum_brightness: !input minimum_brightness
  hysteresis: !input hysteresis
  transition: !input transition
  disable_when_on: !input disable_when_on
  unoccupied_duration: !input unoccupied_duration
  presence_sensor: !input presence_sensor

# TODO: separate automation to turn off auto-toggle switches if a light changes state manually (user_id is set in event data)

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input toggle_switch
    to: 'on'
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input brightness_override_entity
  - platform: time_pattern
    minutes: !input time_pattern_minutes
    seconds: !input time_pattern_seconds

condition:
  - condition: state
    entity_id: !input toggle_switch
    state: 'on'
  - condition: template
    value_template: >-
      {% if disable_when_on is not defined %}
        true
      {% else %}
        {{ expand(disable_when_on)|map(attribute="state")|select("equalto", "on")|list|length == 0 }}
      {% endif %}

# TODO: cooldown?

action:
  - variables:
      light_level: "{{ int(states(light_sensor)) }}"
      threshold: "{{ int(states(light_threshold)) }}"
      trigger_idx: "{{ trigger.idx }}"
  - variables:
      desired_state: >-
        {% if is_state(presence_sensor, 'off') %}
          {% if (now() - states[presence_sensor].last_changed) > timedelta(minutes=unoccupied_duration) %}
            off
          {% else %}
            countdown
          {% endif %}
        {% elif light_level > threshold + hysteresis %}
          off
        {% elif light_level < threshold %}
          on
        {% else %}
          unknown
        {% endif %}
      # map values from 0-100 (light level) to 0-255 (brightness)
      desired_brightness: >-
        {% if threshold == 0 %}
          {{ minimum_brightness }}
        {% else %}
          {{ min([
               max([
                 (threshold - light_level) * 255 / threshold,
                 minimum_brightness,
               ]),
               255
             ])|round }}
        {% endif %}
  - variables:
      desired_transition: >-
        {% if trigger_idx == 0 and desired_state == 'on' %}
          1
        {% elif trigger_idx == 2 %}
          3
        {% else %}
          {{ transition }}
        {% endif %}
      # if brightness_override_entity is set to state
      # then set desired_brightness to min of override and desired
      desired_brightness: >-
        {% if brightness_override_entity is defined and brightness_override_states is defined and brightness_override_states[states(brightness_override_entity)] is defined %}
          {{ min([desired_brightness, brightness_override_states[states(brightness_override_entity)]]) }}
        {% else %}
          {{ desired_brightness }}
        {% endif %}

  - choose:
      # if desired state is off
      - conditions:
          - condition: template
            value_template: "{{ desired_state == 'off' }}"
        # then turn it off 
        sequence:
          - service: light.turn_off
            entity_id: !input lights
            data:
              transition: "{{ desired_transition }}"

      # if desired state is on
      - conditions:
          - condition: template
            value_template: "{{ desired_state == 'on' }}"
        # then set it to desired brightness 
        sequence:
          - service: light.turn_on
            entity_id: !input lights
            data:
              brightness: "{{ desired_brightness }}"
              transition: "{{ desired_transition }}"
