# ------------------------------
# Home presence rules
# Turns lights on/off based on presence
#
- alias: Turn on occupied room lights when sun sets
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    - service: myhome.enable_scene
      entity_id: room.living_room
    - service: myhome.enable_scene
      entity_id: room.bedroom
    - service: myhome.enable_scene
      entity_id: room.kitchen
    - service: myhome.enable_scene
      entity_id: room.hall
- alias: Turn lights off when not home
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights
- alias: Turn on hall light when arriving home
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: myhome.active
    state: 'on'
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.hall

# ------------------------------
# Home mode rules
# Updates the state of the home based on time of day
#
- alias: Morning home mode
  hide_entity: True
  trigger:
    platform: time
    at: '06:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: morning
- alias: Day home mode
  hide_entity: True
  trigger:
    platform: time
    at: '09:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: day
- alias: Afternoon home mode
  hide_entity: True
  trigger:
    platform: time
    at: '13:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: afternoon
- alias: Evening home mode
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: '-01:30:00'
  action:
    service: myhome.set_mode
    data:
      mode: evening
- alias: Night home mode
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: '01:30:00'
  action:
    service: myhome.set_mode
    data:
      mode: night

# ------------------------------
# Motion detector rules
# Updates the state of a room if motion is detected
#
- alias: Bedroom motion detected
  hide_entity: True
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_2_1
  condition: &motion_condition
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: home
      - condition: state
        entity_id: myhome.active
        state: 'on'
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.bedroom
- alias: Hall motion detected
  hide_entity: True
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_5_1
  condition:
    <<: *motion_condition
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.hall
- alias: Living Room motion detected
  hide_entity: True
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_10_1
  condition:
    <<: *motion_condition
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.living_room
- alias: Bookcase motion detected
  hide_entity: True
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_4_1
  condition:
    <<: *motion_condition
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.living_room
- alias: Kitchen motion detected
  hide_entity: True
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_1_1
  condition:
    <<: *motion_condition
  action:
    service: myhome.set_room_occupied
    data:
      entity_id: room.kitchen


# ------------------------------
# Room occupancy rules
#
- alias: Set rooms to unoccupied when away
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: myhome.set_away
- alias: Bedroom occupied
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ is_state_attr("room.bedroom", "mode", "occupied") }}'
  condition:
    condition: template
    value_template: '{{ states("sensor.motion_sensor_2_2") | float <= 9 }}'
  action:
    service: myhome.enable_occupied_scene
    data:
      entity_id: room.bedroom
- alias: Living room occupied
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ is_state_attr("room.living_room", "mode", "occupied") }}'
  condition:
    condition: template
    value_template: '{{ states("sensor.motion_sensor_10_2") | float <= 14 or states("sensor.motion_sensor_4_2") | float <= 7 }}'
  action:
    service: myhome.enable_occupied_scene
    data:
      entity_id: room.living_room
- alias: Hall occupied
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ is_state_attr("room.hall", "mode", "occupied") }}'
  condition:
    condition: template
    value_template: '{{ states("sensor.motion_sensor_5_2") | float <= 20 }}'
  action:
    service: myhome.enable_occupied_scene
    data:
      entity_id: room.hall
- alias: Kitchen occupied
  hide_entity: True
  trigger:
    platform: template
    value_template: '{{ is_state_attr("room.kitchen", "mode", "occupied") }}'
  condition:
    condition: template
    value_template: '{{ states("sensor.motion_sensor_1_2") | float <= 2 }}'
  action:
    service: myhome.enable_occupied_scene
    data:
      entity_id: room.kitchen

# ------------------------------
# Bed sensor rules
#
- alias: Bed occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor_16_1
    to: 'on'
    for:
      minutes: 2
  condition:
    condition: time
    after: '21:00:00'
  action:
    service: script.bedtime
- alias: Bed not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor_16_1
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
      - condition: time
        after: '21:00:00'
      - condition: state
        entity_id: script.bedtime
        state: 'on'
  action:
    service: script.turn_off
    entity_id: script.bedtime
