# ------------------------------
# Home presence rules
# Turns lights on/off based on presence
#
- alias: Turn on light when sun sets or arriving home
  trigger:
    - platform: sun
      event: sunset
      offset: "-01:00:00"
    - platform: state
      entity_id: group.all_devices
      state: home
  condition:
    platform: state
    entity_id: group.all_devices
    state: home
  action:
    service: light.turn_on
    entity_id: group.living_room
- alias: Turn lights off when not home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: group.all_lights

# ------------------------------
# Home mode rules
# Updates the state of the home based on time of day
#
- alias: Morning home mode
  trigger:
    platform: time
    after: '06:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: morning
- alias: Day home mode
  trigger:
    platform: time
    after: '09:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: day
- alias: Afternoon home mode
  trigger:
    platform: time
    after: '13:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: afternoon
- alias: Evening home mode
  trigger:
    platform: sun
    event: sunset
    offset: '-02:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: evening
- alias: Night home mode
  trigger:
    platform: sun
    event: sunset
    offset: '01:00:00'
  action:
    service: myhome.set_mode
    data:
      mode: night

# ------------------------------
# Motion detector rules
# Updates the state of a room if motion is detected
#
- &motion
  alias: Bedroom motion detected
  trigger: &motion_trigger
    platform: state
    entity_id: sensor.motion_sensor_21
    to: 'on'
  condition:
    platform: state
    entity_id: group.all_devices
    state: home
  action: &motion_action
    service: myhome.set_occupied
    data:
      entity_id: room.bedroom
- <<: *motion
  alias: Hall motion detected
  trigger:
    <<: *motion_trigger
    entity_id: sensor.motion_sensor_51
  action:
    <<: *motion_action
    data:
      entity_id: room.hall
- <<: *motion
  alias: Living Room motion detected
  trigger:
    <<: *motion_trigger
    entity_id: sensor.motion_sensor_101
  action:
    <<: *motion_action
    data:
      entity_id: room.living_room
- <<: *motion
  alias: Bookcase motion detected
  trigger:
    <<: *motion_trigger
    entity_id: sensor.motion_sensor_41
  action:
    <<: *motion_action
    data:
      entity_id: room.living_room
- <<: *motion
  alias: Kitchen motion detected
  trigger:
    <<: *motion_trigger
    entity_id: sensor.motion_sensor_11
  action:
    <<: *motion_action
    data:
      entity_id: room.kitchen


# ------------------------------
# Room occupancy rules
#
- alias: Set rooms to unoccupied when away
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: myhome.set_away
- &occupied
  alias: Bedroom occupied
  trigger: &occupied_trigger
    platform: state
    entity_id: room.bedroom
    from: 'not_occupied'
    to: 'occupied'
  condition: &occupied_condition
    platform: template
    value_template: '{{ states.sensor.motion_sensor_22 | float <= 12 }}'
  action: &occupied_action
    service: myhome.set_scene
    data:
      entity_id: room.bedroom
- <<: *occupied
  alias: Living room occupied
  trigger:
    <<: *occupied_trigger
    entity_id: room.living_room
  condition:
    <<: *occupied_condition
    value_template: '{{ states.sensor.motion_sensor_102 | float <= 16 or states.sensor.motion_sensor_42 | float <= 12 }}'
  action:
    <<: *occupied_action
    data:
      entity_id: room.living_room
- <<: *occupied
  alias: Hall occupied
  trigger:
    <<: *occupied_trigger
    entity_id: room.hall
  condition:
    <<: *occupied_condition
    value_template: '{{ states.sensor.motion_sensor_52 | float <= 12 }}'
  action:
    <<: *occupied_action
    data:
      entity_id: room.hall
- <<: *occupied
  alias: Kitchen occupied
  trigger:
    <<: *occupied_trigger
    entity_id: room.kitchen
  condition:
    <<: *occupied_condition
    value_template: '{{ states.sensor.motion_sensor_12 | float <= 15 }}'
  action:
    <<: *occupied_action
    data:
      entity_id: room.kitchen
