# ------------------------------
# Bed sensor rules
#
- alias: Bed occupied
  trigger:
    platform: state
    entity_id: sensor.bed_occupied
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    service: myhome.set_touch
    data:
      entity_id: sensor.touch_controller_13_1
      command: 5

- alias: Bed triggers nighttime
  trigger:
    platform: state
    entity_id: sensor.bed_occupied
    to: 'on'
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    - service: script.bedtime
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_dnd"
        title: "alarms_only"

- alias: Bed not occupied DND
  trigger:
    platform: state
    entity_id: sensor.bed_occupied
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_dnd"
        title: "off"

- alias: Bed not occupied
  trigger:
    platform: state
    entity_id: sensor.bed_occupied
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: script.bedtime
        state: 'on'
  action:
    service: script.turn_off
    entity_id: script.bedtime

- alias: Reset bed when not occupied
  trigger:
    platform: state
    entity_id: sensor.bed_occupied
    to: 'off'
    for:
      minutes: 60
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Morning
      - condition: state
        entity_id: input_select.myhome_mode
        state: Day
  action:
    service: script.turn_on
    entity_id: script.reset_bed

- alias: Notify disconnected sensors
  trigger:
    - platform: numeric_state
      entity_id: sensor.bed_sensor_16_2
      above: 90
    - platform: numeric_state
      entity_id: sensor.bed_sensor_16_3
      above: 90
    - platform: numeric_state
      entity_id: sensor.bed_sensor_16_4
      above: 70
    - platform: numeric_state
      entity_id: sensor.bed_sensor_16_5
      above: 70
  action:
    service: notify.mobile_app_pixel_3a_xl
    data:
      message: Check the bed sensors
      title: Bed sensor disconnected
      data:
        clickAction: "/lovelace/3"
        actions:
          - action: "reset"
            title: "Reset"

- alias: Reset bed notification action
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: reset
  action:
    service: script.turn_on
    entity_id: script.reset_bed
