# ------------------------------
# Bed sensor rules
#
- alias: Bed occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor_16_1
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    service: myhome.set_touch
    data:
      entity_id: sensor.touch_controller_13_1
      command: 5
- alias: Bed triggers nighttime
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor_16_1
    to: 'on'
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    service: script.bedtime
- alias: Bed not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: binary_sensor.bed_sensor_16_1
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.myhome_mode
        state: Night
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: script.bedtime
        state: 'on'
  action:
    service: script.turn_off
    entity_id: script.bedtime
