# ------------------------------
# Database automations
#
- alias: Purge entities hourly
  trigger:
    - platform: time_pattern
      minutes: 0
      seconds: 10
  action:
    service: myhome.purge
    data:
      entities:
        - sensor.load_1m
        - sensor.load_5m
        - sensor.load_15m
        - sensor.processor_use
        - sensor.memory_use
        - sensor.memory_free
        - sensor.swap_use
        - sensor.swap_free
      keep:
        hours: 12

- alias: Purge entities daily
  trigger:
    - platform: time
      at: '03:02:10'
  action:
    service: myhome.purge
    data:
      entities:
        - sensor.living_room_threshold
        - sensor.kitchen_threshold
        - sensor.bedroom_threshold
        - sensor.dining_room_threshold
        - sensor.motion_sensor_1_1
        - sensor.motion_sensor_2_1
        - sensor.motion_sensor_4_1
        - sensor.motion_sensor_5_1
        - sensor.motion_sensor_10_1
        - sensor.motion_sensor_1_2
        - sensor.motion_sensor_2_2
        - sensor.motion_sensor_4_2
        - sensor.motion_sensor_5_2
        - sensor.motion_sensor_10_2
        - input_number.living_room_threshold
        - input_number.kitchen_threshold
        - input_number.bedroom_threshold
        - input_number.dining_room_threshold
      keep:
        days: 1
