# ------------------------------
# Default view group visibility rules
#
- alias: Bedroom visible
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.bedroom
  action:
    service: group.set_visibility
    data_template:
      entity_id: group.default_bedroom
      visible: '{{ states("room.bedroom") in ["occupied", "countdown"] }}'

- alias: Living room visible
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.living_room
  action:
    service: group.set_visibility
    data_template:
      entity_id: group.default_living_room
      visible: '{{ states("room.living_room") in ["occupied", "countdown"] }}'

- alias: Kitchen visible
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.kitchen
  action:
    service: group.set_visibility
    data_template:
      entity_id: group.default_kitchen
      visible: '{{ states("room.kitchen") in ["occupied", "countdown"] }}'

- alias: Hall visible
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.hall
  action:
    service: group.set_visibility
    data_template:
      entity_id: group.default_hall
      visible: '{{ states("room.hall") in ["occupied", "countdown"] }}'
