# ------------------------------
# Media automations
#
- alias: Fire TV media mode
  hide_entity: True
  trigger:
    # listing each state is a workaround so this is not
    # triggered by attribute changes
    - platform: state
      entity_id: media_player.fire_tv
      to: 'playing'
    - platform: state
      entity_id: media_player.fire_tv
      to: 'paused'
    - platform: state
      entity_id: media_player.fire_tv
      to: 'standby'
    - platform: state
      entity_id: media_player.fire_tv
      to: 'idle'
    - platform: state
      entity_id: media_player.fire_tv
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {% set mode = states("input_select.media_mode") %}
            {% if mode != "Off" %}true{% endif %}
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.media_mode
      option: >
          {% if is_state('media_player.fire_tv', 'playing') %}
          {% set source = state_attr('media_player.fire_tv', 'source') %}
          {% if source in ('com.amazon.avod', 'com.netflix.ninja') %}
          Movie
          {% else %}
          TV
          {% endif %}
          {% elif is_state('media_player.fire_tv', 'paused') %}
          Paused
          {% elif is_state('media_player.fire_tv', 'standby') %}
          Menu
          {% elif is_state('media_player.fire_tv', 'idle') or is_state('media_player.fire_tv', 'off') %}
          Idle
          {% endif %}

- alias: TV backlight on HDMI
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.media_mode
      to: 'TV'
    - platform: state
      entity_id: input_select.media_mode
      to: 'Movie'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {% set mode = states("input_select.media_mode") %}
            {% if mode != "Off" %}true{% endif %}
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    - delay: '00:00:06'
    - service: light.turn_on
      data_template:
        entity_id: light.hyperion
        effect: "Menu fade off"
    - delay: '00:00:03'
    - service: light.turn_on
      data_template:
        entity_id: light.hyperion
        effect: HDMI

- alias: TV backlight on solid
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.media_mode
      to: 'Paused'
    - platform: state
      entity_id: input_select.media_mode
      to: 'Menu'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {% set mode = states("input_select.media_mode") %}
            {% if mode != "Off" %}true{% endif %}
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hyperion
        effect: "Menu fade on"

- alias: TV backlight off
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.media_mode
      to: 'Idle'
    - platform: state
      entity_id: media_player.hdmi_0
      to: 'off'
    - platform: state
      entity_id: media_player.samsung_tv
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
            {% set mode = states("input_select.media_mode") %}
            {% if mode != "Off" %}true{% endif %}
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hyperion
        effect: "Menu fade off"
    - delay: '00:00:03'
    - service: light.turn_off
      data:
        entity_id: light.hyperion

- alias: All lights off for movies
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_select.media_mode
      to: 'Movie'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: room.living_room
        state: 'occupied'
  action:
    service: light.turn_off
    data:
      entity_id:
        - group.bedroom
        - group.kitchen
        - group.hall
      transition: 3
