# ------------------------------
# Motion detector rules
# Updates the state of a room if motion is detected
#
- alias: Bedroom motion detected
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_2_1
  condition: &motion_condition
    condition: and
    conditions:
      - condition: state
        entity_id: person.andrew
        state: home
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: template
        value_template: '{{ not is_state("room.bedroom", "occupied") }}'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.bedroom
      state: 'occupied'

- alias: Office motion detected
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_5_1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.andrew
        state: home
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: template
        value_template: '{{ not is_state("room.office", "occupied") }}'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.office
      state: 'occupied'

- alias: Living Room motion detected
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_10_1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.andrew
        state: home
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: template
        value_template: '{{ not is_state("room.living_room", "occupied") }}'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.living_room
      state: 'occupied'

- alias: Bookcase motion detected
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_4_1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.andrew
        state: home
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: template
        value_template: '{{ not is_state("room.living_room", "occupied") }}'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.living_room
      state: 'occupied'

- alias: Kitchen motion detected
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.motion_sensor_1_1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: person.andrew
        state: home
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: template
        value_template: '{{ not is_state("room.kitchen", "occupied") }}'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.kitchen
      state: 'occupied'
