# ------------------------------
# Notification rules
#

- alias: Turn bluetooth on when leaving
  trigger:
    - platform: state
      entity_id: device_tracker.rfid_sensor_12_1
      to: 'not_home'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_bluetooth"
        title: "turn_on"

- alias: Turn bluetooth off when arriving
  trigger:
    - platform: state
      entity_id: device_tracker.rfid_sensor_12_1
      to: 'home'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_bluetooth"
        title: "turn_off"
