# ------------------------------
# Notification rules
#

- alias: Turn bluetooth on when leaving
  trigger:
    - platform: state
      entity_id: device_tracker.rfid_sensor_12_1
      to: 'not_home'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_bluetooth"
        title: "turn_on"

- alias: Turn bluetooth off when arriving
  trigger:
    - platform: state
      entity_id: device_tracker.rfid_sensor_12_1
      to: 'home'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "command_bluetooth"
        title: "turn_off"

- alias: Turn off alarm reminder for vacations
  trigger:
    - platform: time
      at: "19:00:00"
  condition:
    # if vacation starts less than a day away
    - condition: template
      value_template: "{{ (state_attr('calendar.vacation', 'start_time')|as_timestamp)|round <= (now() + timedelta(days=1))|as_timestamp|round }}"
    # and the next alarm is set (i.e. not unavailable)
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.pixel_3a_xl_next_alarm
          state: 'unavailable'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "Vacaction starts tomorrow but your alarm is still set."
        title: "Vacation start"
        data:
          actions:
            - action: "URI"
              uri: "app://com.google.android.deskclock"
              title: "Open Alarms"

- alias: Turn on alarm reminder for vacations
  trigger:
    - platform: time
      at: "19:00:00"
  condition:
    # if vacation ends less than a day away
    - condition: template
      value_template: "{{ (state_attr('calendar.vacation', 'end_time')|as_timestamp)|round <= (now() + timedelta(days=1))|as_timestamp|round }}"
    # and the next alarm is not set
    - condition: state
      entity_id: sensor.pixel_3a_xl_next_alarm
      state: 'unavailable'
  action:
    - service: notify.mobile_app_pixel_3a_xl
      data:
        message: "Vacaction ends tomorrow but your alarm is not set."
        title: "Vacation end"
        data:
          actions:
            - action: "URI"
              uri: "app://com.google.android.deskclock"
              title: "Open Alarms"
