# ------------------------------
# Room occupancy rules
#
- alias: Set rooms to unoccupied when away
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: python_script.set_away

- alias: Bedroom countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.bedroom
    to: 'countdown'
    for:
      minutes: 10
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.bedroom
        state: not_occupied

- alias: Living room countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.living_room
    to: 'countdown'
    for:
      minutes: 20
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.living_room
        state: not_occupied

- alias: Hall countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.hall
    to: 'countdown'
    for:
      minutes: 5
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.hall
        state: not_occupied

- alias: Kitchen countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.kitchen
    to: 'countdown'
    for:
      minutes: 7
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.kitchen
        state: not_occupied

# disable autolight updates for kitchen when manually set at the switch
- alias: Autoupdate Kitchen Override
  hide_entity: True
  trigger:
    - platform: template
      value_template: "{{ state_attr('light.rgbw_15_1', 'V_VAR2') == '1' }}"
    - platform: template
      value_template: "{{ state_attr('light.rgbw_15_2', 'V_VAR2') == '1' }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.auto_kitchen
