# ------------------------------
# Room occupancy rules
#
- alias: Set rooms to unoccupied when away
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: python_script.set_away

- alias: Update occupied room
  hide_entity: True
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.myhome_active
    state: 'on'
  action:
    service: python_script.update_occupied_room

- alias: Bedroom occupied
  hide_entity: True
  trigger:
    - platform: state
      entity_id: room.bedroom
      to: 'occupied'
      from: 'not_occupied'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_bedroom
        state: 'on'
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: input_boolean.room_bedroom
        state: 'on'
      - condition: state
        entity_id: room.bedroom
        state: 'occupied'
  action:
    service: python_script.enable_room_scene
    data:
      room: bedroom
- alias: Bedroom countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.bedroom
    to: 'countdown'
    for:
      minutes: 10
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.bedroom
        state: not_occupied
- alias: Bedroom not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.bedroom
    to: 'not_occupied'
    for:
      seconds: 5
  action:
    service: python_script.enable_room_scene
    data:
      room: bedroom

- alias: Living room occupied
  hide_entity: True
  trigger:
    - platform: state
      entity_id: room.living_room
      to: 'occupied'
      from: 'not_occupied'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_living_room
        state: 'on'
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: input_boolean.room_living_room
        state: 'on'
      - condition: state
        entity_id: room.living_room
        state: 'occupied'
  action:
    service: python_script.enable_room_scene
    data:
      room: living_room
- alias: Living room countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.living_room
    to: 'countdown'
    for:
      minutes: 20
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.living_room
        state: not_occupied
- alias: Living room not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.living_room
    to: 'not_occupied'
    for:
      seconds: 5
  action:
    service: python_script.enable_room_scene
    data:
      room: living_room

- alias: Hall occupied
  hide_entity: True
  trigger:
    - platform: state
      entity_id: room.hall
      to: 'occupied'
      from: 'not_occupied'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_hall
        state: 'on'
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: input_boolean.room_hall
        state: 'on'
      - condition: state
        entity_id: room.hall
        state: 'occupied'
  action:
    service: python_script.enable_room_scene
    data:
      room: hall
- alias: Hall countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.hall
    to: 'countdown'
    for:
      minutes: 5
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.hall
        state: not_occupied
- alias: Hall not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.hall
    to: 'not_occupied'
    for:
      seconds: 5
  action:
    service: python_script.enable_room_scene
    data:
      room: hall

- alias: Kitchen occupied
  hide_entity: True
  trigger:
    - platform: state
      entity_id: room.kitchen
      to: 'occupied'
      from: 'not_occupied'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_kitchen
        state: 'on'
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: input_boolean.room_kitchen
        state: 'on'
      - condition: state
        entity_id: room.kitchen
        state: 'occupied'
  action:
    service: python_script.enable_room_scene
    data:
      room: kitchen
- alias: Kitchen countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.kitchen
    to: 'countdown'
    for:
      minutes: 7
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.kitchen
        state: not_occupied
- alias: Kitchen not occupied
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.kitchen
    to: 'not_occupied'
    for:
      seconds: 5
  action:
    service: python_script.enable_room_scene
    data:
      room: kitchen
