# ------------------------------
# Room occupancy rules
#
- alias: Set rooms to unoccupied when away
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: python_script.set_away

- alias: Bedroom countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.bedroom
    to: 'countdown'
    for:
      minutes: 10
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.bedroom
        state: not_occupied

- alias: Living room countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.living_room
    to: 'countdown'
    for:
      minutes: 20
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.living_room
        state: not_occupied

- alias: Hall countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.hall
    to: 'countdown'
    for:
      minutes: 5
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.hall
        state: not_occupied

- alias: Kitchen countdown
  hide_entity: True
  trigger:
    platform: state
    entity_id: room.kitchen
    to: 'countdown'
    for:
      minutes: 7
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.kitchen
        state: not_occupied
