# ------------------------------
# Home presence rules
# Turns lights on/off based on presence
#

- alias: Turn lights off when not home
  trigger:
    platform: state
    entity_id: person.andrew
    from: 'home'
    to: 'not_home'
  action:
    service: light.turn_off
    entity_id: all

- alias: Turn on kitchen light when arriving home
  trigger:
    platform: state
    entity_id: person.andrew
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.myhome_active
    state: 'on'
  action:
    service: python_script.set_room_state
    data:
      entity_id: room.kitchen
      state: 'occupied'

- alias: Turn off lights when leaving on weekdays
  trigger:
    - platform: state
      entity_id: device_tracker.rfid_sensor_12_1
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
      - condition: state
        entity_id: binary_sensor.weekday
        state: 'on'
      - condition: state
        entity_id: device_tracker.rfid_sensor_12_1
        state: 'not_home'
      - condition: time
        after: '07:30:00'
        before: '09:30:00'
  action:
    - service: light.turn_off
      entity_id:
        - group.kitchen
        - group.living_room
        - group.bedroom
        - group.dining_room

- alias: Turn off bedroom lights on weekday mornings
  trigger:
    - platform: state
      entity_id: room.office
      to: "occupied"
      for: "00:20:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.myhome_active
        state: "on"
      - condition: state
        entity_id: binary_sensor.weekday
        state: "on"
      - condition: time
        after: "06:00:00"
        before: "10:00:00"
  action:
    - service: light.turn_off
      entity_id:
        - group.bedroom
