# ------------------------------
# Startup rules
#
- alias: 'Initialize rooms on start'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: python_script.set_room_state
      data:
        entity_id: room.bedroom
        state: 'not_occupied'
    - service: python_script.set_room_state
      data:
        entity_id: room.living_room
        state: 'not_occupied'
    - service: python_script.set_room_state
      data:
        entity_id: room.kitchen
        state: 'not_occupied'
    - service: python_script.set_room_state
      data:
        entity_id: room.dining_room
        state: 'not_occupied'
    - service: python_script.set_room_state
      data:
        entity_id: room.office
        state: 'not_occupied'

- alias: 'Reset lights on start'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: input_boolean.maintenance_mode
    state: 'off'
  action:
    - service: script.all_off
