- alias: 'Set dark theme for night'
  trigger:
    - platform: state
      entity_id: input_select.myhome_mode
      to: 'Night'
  condition:
    condition: state
    entity_id: input_boolean.autodark_theme
    state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: 'input_select.current_theme'
        option: 'Google Dark Theme'

- alias: 'Set light theme for morning'
  trigger:
    - platform: state
      entity_id: input_select.myhome_mode
      to: 'Morning'
  condition:
    condition: state
    entity_id: input_boolean.autodark_theme
    state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: 'input_select.current_theme'
        option: 'Google Light Theme'

- alias: 'Update theme from select'
  trigger:
    - platform: state
      entity_id: input_select.current_theme
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data_template:
        name: '{{states.input_select.current_theme.state}}' 
