# ------------------------------
# Wakeup rules
#
- alias: Wake-up
  trigger:
    platform: time
    at: '06:38:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: calendar.vacation
        state: 'off'
      - condition: state
        entity_id: binary_sensor.weekday
        state: 'on'
      - condition: state
        entity_id: room.bedroom
        state: 'occupied'
      - condition: state
        entity_id: input_boolean.myhome_active
        state: 'on'
  action:
    service: script.turn_on
    entity_id: script.wakeup
